[project]
name = "doclinglibx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Shore", email = "jobs_raceway0p@icloud.com" }
]
requires-python = ">=3.14"
dependencies = [
    "docling>=2.123.1",
]

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
]
